In [36]:
# Initial imports
import pandas as pd
from pathlib import Path
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [37]:
# Loading and Preprocessing
# file_path = Path("C:/Users/sqali/OneDrive/Desktop/bootcampUSE/Projects/Project 4/U.S._Chronic_Disease_Indicators__CDI_.csv")
df_data = pd.read_csv(file_path)
print("Sample Data:")

C:\Users\sqali\AppData\Local\Temp\ipykernel_11296\847086371.py:3: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_data = pd.read_csv(file_path)

Sample Data:

In [38]:
# df_data.columns

In [39]:
# Check column names
print("Column Names:")
df_data.columns

Column Names:

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'DataSource',
       'Topic', 'Question', 'Response', 'DataValueUnit', 'DataValueType',
       'DataValue', 'DataValueAlt', 'DataValueFootnoteSymbol',
       'DatavalueFootnote', 'LowConfidenceLimit', 'HighConfidenceLimit',
       'StratificationCategory1', 'Stratification1', 'StratificationCategory2',
       'Stratification2', 'StratificationCategory3', 'Stratification3',
       'GeoLocation', 'ResponseID', 'LocationID', 'TopicID', 'QuestionID',
       'DataValueTypeID', 'StratificationCategoryID1', 'StratificationID1',
       'StratificationCategoryID2', 'StratificationID2',
       'StratificationCategoryID3', 'StratificationID3'],
      dtype='object')

In [40]:
df_data.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2010,2010,OR,Oregon,NVSS,Cardiovascular Disease,Mortality from heart failure,NaN,NaN,Number,...,41,CVD,CVD1_4,NMBR,RACE,AIAN,NaN,NaN,NaN,NaN
1,2019,2019,AZ,Arizona,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,4,ALC,ALC1_1,CRDPREV,GENDER,GENF,NaN,NaN,NaN,NaN
2,2019,2019,OH,Ohio,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,39,ALC,ALC1_1,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN
3,2019,2019,US,United States,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,59,ALC,ALC1_1,CRDPREV,RACE,ASN,NaN,NaN,NaN,NaN
4,2015,2015,VI,Virgin Islands,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,78,ALC,ALC1_1,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN

In [41]:
# Filter the DataFrame to include only rows where the "Topic" column is "Diabetes"
df_data_diabetes = df_data[df_data['Topic'] == 'Diabetes']

In [42]:
# Updated rows
print("remaining row",df_data_diabetes.shape)
df_data_diabetes.head()

remaining row (132912, 34)

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
1407,2011,2011,NV,Nevada,BRFSS,Diabetes,Prevalence of diagnosed diabetes among adults ...,NaN,%,Age-adjusted Prevalence,...,32,DIA,DIA2_1,AGEADJPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
1429,2016,2016,NV,Nevada,BRFSS,Diabetes,Visits to dentist or dental clinic among adult...,NaN,%,Crude Prevalence,...,32,DIA,DIA8_0,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN
1572,2019,2019,NV,Nevada,BRFSS,Diabetes,Prevalence of diagnosed diabetes among adults ...,NaN,%,Crude Prevalence,...,32,DIA,DIA2_1,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN
1580,2019,2019,NV,Nevada,BRFSS,Diabetes,Foot examination among adults aged >= 18 years...,NaN,%,Crude Prevalence,...,32,DIA,DIA5_0,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN
1598,2017,2017,NE,Nebraska,BRFSS,Diabetes,Prevalence of high cholesterol among adults ag...,NaN,%,Crude Prevalence,...,31,DIA,DIA11_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN

In [43]:
df_data_diabetes.isnull().sum()

YearStart                         0
YearEnd                           0
LocationAbbr                      0
LocationDesc                      0
DataSource                        0
Topic                             0
Question                          0
Response                     132912
DataValueUnit                 12578
DataValueType                     0
DataValue                     59996
DataValueAlt                  59996
DataValueFootnoteSymbol       71922
DatavalueFootnote             71922
LowConfidenceLimit            68068
HighConfidenceLimit           68068
StratificationCategory1           0
Stratification1                   0
StratificationCategory2      132912
Stratification2              132912
StratificationCategory3      132912
Stratification3              132912
GeoLocation                      92
ResponseID                   132912
LocationID                        0
TopicID                           0
QuestionID                        0
DataValueTypeID                   0
StratificationCategoryID1         0
StratificationID1                 0
StratificationCategoryID2    132912
StratificationID2            132912
StratificationCategoryID3    132912
StratificationID3            132912
dtype: int64

In [44]:
# Define a list of columns to drop
columns_to_drop = ['StratificationCategoryID2', 'StratificationID2', 'StratificationCategoryID3','StratificationID3','StratificationCategory3','Stratification3','Response']

In [45]:
# Display the list of columns to drop
print("Columns to Drop:")
columns_to_drop

Columns to Drop:

['StratificationCategoryID2',
 'StratificationID2',
 'StratificationCategoryID3',
 'StratificationID3',
 'StratificationCategory3',
 'Stratification3',
 'Response']

In [46]:
# Drop the specified columns from the DataFrame
df_data.drop(columns_to_drop, axis=1, inplace=True)

# Filter the DataFrame to include only rows related to diabetes
df_data_diabetes = df_data[df_data['Topic'] == 'Diabetes']

# Print the DataFrame to see the remaining columns related to diabetes
print("DataFrame after dropping columns and filtering for diabetes")
df_data_diabetes.head()

DataFrame after dropping columns and filtering for diabetes

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,DataValueUnit,DataValueType,DataValue,...,StratificationCategory2,Stratification2,GeoLocation,ResponseID,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1
1407,2011,2011,NV,Nevada,BRFSS,Diabetes,Prevalence of diagnosed diabetes among adults ...,%,Age-adjusted Prevalence,10,...,NaN,NaN,POINT (-117.07184056399967 39.493240390000494),NaN,32,DIA,DIA2_1,AGEADJPREV,OVERALL,OVR
1429,2016,2016,NV,Nevada,BRFSS,Diabetes,Visits to dentist or dental clinic among adult...,%,Crude Prevalence,57.8,...,NaN,NaN,POINT (-117.07184056399967 39.493240390000494),NaN,32,DIA,DIA8_0,CRDPREV,GENDER,GENM
1572,2019,2019,NV,Nevada,BRFSS,Diabetes,Prevalence of diagnosed diabetes among adults ...,%,Crude Prevalence,11.2,...,NaN,NaN,POINT (-117.07184056399967 39.493240390000494),NaN,32,DIA,DIA2_1,CRDPREV,GENDER,GENM
1580,2019,2019,NV,Nevada,BRFSS,Diabetes,Foot examination among adults aged >= 18 years...,%,Crude Prevalence,NaN,...,NaN,NaN,POINT (-117.07184056399967 39.493240390000494),NaN,32,DIA,DIA5_0,CRDPREV,GENDER,GENM
1598,2017,2017,NE,Nebraska,BRFSS,Diabetes,Prevalence of high cholesterol among adults ag...,%,Crude Prevalence,56.9,...,NaN,NaN,POINT (-99.36572062299967 41.6410409880005),NaN,31,DIA,DIA11_1,CRDPREV,OVERALL,OVR

In [35]:
# Define features set (X) and target variable (y)
# X = df_data.drop(columns_to_drop, axis=1)
# y = df_data["Diabetes"]

In [13]:
# Splitting into Train and Test sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [ ]:
# Creating StandardScaler instance
scaler = StandardScaler()

In [ ]:
# Fitting StandardScaler
X_scaler = scaler.fit(X_train)

In [ ]:
# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# Creating the decision tree classifier instance or  can user other models
model = tree.DecisionTreeClassifier()
model = model.fit(X_train_scaled, y_train)

In [ ]:
# Fitting the model
model = model.fit(X_train_scaled, y_train)

In [ ]:
# Making predictions using the testing data
predictions = model.predict(X_test_scaled)

In [ ]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)

In [ ]:
# Displaying results
print("\nConfusion Matrix:")
display(cm_df)
print(f"\nAccuracy Score: {acc_score:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, predictions))